version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - ruby/install-deps
  run_spec:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run: rspec spec --out "/tmp/test-results/rspec"/results.xml --format progress

workflows:
  build_and_test:
    jobs:
      - build
      - run_spec:
          requires:
            - build