version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
  run_spec:
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - run: bundle install
      - run: mkdir ~/rspec
      - run: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

workflows:
  build_and_test:
    jobs:
      - build
      - run_spec:
          requires:
            - build
          matrix:
            parameters:
              # Available versions can be viewed here:
              # https://github.com/CircleCI-Public/cimg-ruby
              ruby-version: ['3.0', '3.1', '3.2']